language: generic 
sudo: required  
services:
  - docker

script:
  - docker run -e CI=true USERNAME/docker-react npm run test

before_install:
  - docker build -t swarnim0308/docker-react -f Dockerfile.dev .